### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by duhow** [duhow/MultiCRM#1]
- [ ] Implementar Habitica con tareas.
- [ ] Parsear llamadas CDR, insertar en una tabla y vía *cron* procesar y asignar al usuario / extensión correspondiente, coincidir por hora más cercana sobre la indicación apuntada por el usuario (interesado, no interesado, cuelga...)
- [ ] Integración Mailchimp, información y estadísticas sobre el mail, sobre más de una lista / campaña?
- [ ] Enviar mail vía server o Mailchimp incluyendo información.
- [ ] Integración Prestashop, ver info cliente, direcciones, pedidos, pago, estado. *WEBSERVICE* vía URL + ID tienda.
